#!/usr/bin/env bash
# vim: set ft=sh:

# Look for keywords in the args
#
for opt in $@; do
  case ${opt} in
    kill) opt_kill=true;;
    nocache) build_opts="${build_opts} -no-cache";;
    push) opt_push=true;;
    *) tag=_${opt};rev=${opt};;
  esac
done

[ -z "${tag}" ] && tag=_dev && rev=dev

# Stop any processes running that look like they are ours, unless we are told not to 'nokill'
#
if [ -n "${opt_kill}" ]; then
  docker ps | grep rickalm.centos | awk '{print $1}' | xargs -n 1 docker rm
  docker ps | grep uptake.dcos | awk '{print $1}' | xargs -n 1 docker rm
  docker ps -a -q | xargs docker rm
fi

# Build our base containers
#
docker build ${build_opts} -f Dockerfile.dcos:1.7_base -t uptake/dcos:1.7_base-${rev} . || exit 1

flavors="master slave dns"
for flavor in ${flavors}; do
  # Build the Master/Slave containers based on base
  #
  cp Dockerfile.dcos:1.7_aws_${flavor} MyDocker
  sed -e "s~FROM .*~FROM uptake/dcos:1.7_base-${rev}~" -i . MyDocker
  docker build ${build_opts} -f MyDocker -t uptake/dcos:1.7_aws_${flavor}-${rev} . || exit 1
  rm MyDocker*
done

# If we are pushing, then do so
#
if [ -n "${opt_push}" ]; then
  for flavor in ${flavors}; do
    docker push uptake/dcos:1.7_aws_${flavor}-${rev} || exit 1
  done
fi

# Clean up our left over images (e.g. tagged <none>) to free disk space
#
docker images | grep none | awk '{print $3}' | xargs docker rmi
