#!/bin/bash
ip=$(/opt/mesosphere/bin/detect_ip)
if [[ "$ip" =~ ^([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})$ ]];then
  for (( i=1; i<${#BASH_REMATCH[@]}; ++i ))
    do
      (( ${BASH_REMATCH[$i]} <= 255 )) || { echo "Not a valid ip $ip" >&2; exit 1; }
    done
else
  echo "Not a valid ip: $ip" >&2
  exit 1;
fi
